In [1]:
import numpy as np
v1=np.arange(3).reshape((1,3))
v1

array([[0, 1, 2]])

In [2]:
v1.shape

(1, 3)

In [4]:
v2=np.arange(6).reshape((3,2))
v2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [5]:
np.dot(v1,v2)

array([[10, 13]])

In [6]:
np.matrix(v1)*np.matrix(v2) #  转换成矩阵



matrix([[10, 13]])