In [2]:
import numpy as np
arr=np.random.randint(1,50,(3,4))
arr

array([[11, 26, 16, 22],
       [46, 14, 43, 33],
       [38, 41, 42, 49]])

In [3]:
arr.max()

49

In [4]:
arr.min()

11

In [5]:
arr.max(axis=0)

array([46, 41, 43, 49])

In [6]:
arr.max(axis=1)

array([26, 46, 49])