In [1]:
import numpy as np
a=[3,1,2]
a=[3,4,6] # 累和
arr=np.array([3,1,2])
arr

array([3, 1, 2])

In [2]:
arr.cumsum() # 累和

array([3, 4, 6], dtype=int32)

In [4]:
arr=np.random.randint(1,5,(2,3))
arr

array([[4, 1, 1],
       [1, 3, 3]])

In [5]:
arr.cumsum(axis=0)  # 列 累和

array([[4, 1, 1],
       [5, 4, 4]], dtype=int32)

In [8]:
arr=np.random.randint(1,5,(2,3))
arr.cumprod() # 累乘

array([  3,   9,  18,  54,  54, 108], dtype=int32)

In [9]:
arr

array([[3, 3, 2],
       [3, 1, 2]])

In [10]:
arr.cumprod(axis=0) 

array([[3, 3, 2],
       [9, 3, 4]], dtype=int32)

In [ ]:
arr.