In [2]:
import numpy as np
arr=np.random.randint(1,5,(3,3))
arr

array([[2, 1, 2],
       [2, 4, 4],
       [2, 2, 4]])

In [3]:
arr.trace()  # 主对角线的元素之和

10

In [4]:
arr2=np.random.randint(1,10,(2,3,4))
arr2

array([[[5, 5, 3, 6],
        [8, 9, 6, 7],
        [4, 8, 7, 6]],

       [[1, 7, 6, 8],
        [4, 7, 6, 9],
        [6, 6, 1, 2]]])

In [5]:
arr2.trace()  # 5+4 5+7 3+6 6+9

array([ 9, 12,  9, 15])

In [7]:
arr2.trace(axis1=1,axis2=2)  # 5+9+7  1+7=1

array([21,  9])