In [3]:
import numpy as np
arr=np.random.randint(1,10,(2,3)) # 二维数组
arr

array([[7, 9, 1],
       [2, 3, 3]])

In [4]:
arr.flatten() # 按行展平  方法一

array([7, 9, 1, 2, 3, 3])

In [5]:
arr.flatten('F') # 按列展平

array([7, 2, 9, 3, 1, 3])

In [6]:
arr.ravel()  #  按行展平 方法二

array([7, 9, 1, 2, 3, 3])

In [7]:
arr.ravel('F') # 按列展平

array([7, 2, 9, 3, 1, 3])

In [8]:
arr.flatten()[0]=10  # 数组元素并没有变化
arr

array([[7, 9, 1],
       [2, 3, 3]])

In [9]:
arr.ravel()[0]=10  # 数组元素发生变化
arr

array([[10,  9,  1],
       [ 2,  3,  3]])