In [1]:
import numpy as np
arr=np.random.randint(1,10,(2,3))
arr

array([[1, 1, 4],
       [7, 6, 6]])

In [3]:
arr.repeat(2,axis=0) # 行 复制两份

array([[1, 1, 4],
       [1, 1, 4],
       [7, 6, 6],
       [7, 6, 6]])

In [5]:
arr.repeat(3,axis=1)  # 列复制 3份 

array([[1, 1, 1, 1, 1, 1, 4, 4, 4],
       [7, 7, 7, 6, 6, 6, 6, 6, 6]])