In [1]:
import numpy as np
arr=np.random.randint(1,10,(2,3))
arr

array([[9, 1, 7],
       [3, 1, 6]])

In [2]:
arr.repeat(2,axis=1)

array([[9, 9, 1, 1, 7, 7],
       [3, 3, 1, 1, 6, 6]])

In [3]:
np.tile(arr,2)   #按块复制

array([[9, 1, 7, 9, 1, 7],
       [3, 1, 6, 3, 1, 6]])

In [4]:
np.tile(arr,(2,1)) # 把原来的块看成一个元素  ，形成新的两行一列

array([[9, 1, 7],
       [3, 1, 6],
       [9, 1, 7],
       [3, 1, 6]])

In [6]:
np.tile(arr,(2,2))  #  两行两列

array([[9, 1, 7, 9, 1, 7],
       [3, 1, 6, 3, 1, 6],
       [9, 1, 7, 9, 1, 7],
       [3, 1, 6, 3, 1, 6]])