In [1]:
import numpy as np
arr1=np.random.randint(1,10,(2,3))
arr1

array([[2, 5, 6],
       [2, 5, 6]])

In [2]:
arr2=np.random.randint(1,10,(3,3))
arr2

array([[3, 5, 9],
       [8, 9, 9],
       [9, 3, 5]])

In [4]:
np.vstack((arr1,arr2))  # 合并成五行三列  竖向合并

array([[2, 5, 6],
       [2, 5, 6],
       [3, 5, 9],
       [8, 9, 9],
       [9, 3, 5]])

In [7]:
np.hstack((arr1,arr2[:2,:])) # 合并第二个模块的0到1行  横向合并

array([[2, 5, 6, 3, 5, 9],
       [2, 5, 6, 8, 9, 9]])

In [8]:
np.concatenate((arr1,arr2))  # 竖向合并

array([[2, 5, 6],
       [2, 5, 6],
       [3, 5, 9],
       [8, 9, 9],
       [9, 3, 5]])

In [9]:
np.concatenate((arr1,arr2[:2,:]),axis=1)  # axis=1 水平方向

array([[2, 5, 6, 3, 5, 9],
       [2, 5, 6, 8, 9, 9]])

In [10]:
np.r_[arr1,arr2]    #竖向合并

array([[2, 5, 6],
       [2, 5, 6],
       [3, 5, 9],
       [8, 9, 9],
       [9, 3, 5]])

In [11]:
np.c_[arr1,arr2[:2,:]]  # 横向合并

array([[2, 5, 6, 3, 5, 9],
       [2, 5, 6, 8, 9, 9]])