In [1]:
import numpy as np
arr=np.random.randint(1,10,(2,3))
arr


array([[1, 4, 9],
       [8, 2, 1]])

In [2]:
arr.argmax()  # 展平之后最大值的索引

2

In [3]:
arr.argmin()

0

In [4]:
arr.argmax(axis=0) # 垂直方向最大值的索引

array([1, 0, 0], dtype=int64)

In [5]:
arr.argmin(axis=1)

array([0, 2], dtype=int64)