In [2]:
import numpy as np
np.arange(100)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [3]:
import sys
np.set_printoptions(threshold=sys.maxsize) #完全显示 所有元素
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [4]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [6]:
np.set_printoptions(precision=3)
np.linspace(0,10,100)

array([ 0.   ,  0.101,  0.202,  0.303,  0.404,  0.505,  0.606,  0.707,
        0.808,  0.909,  1.01 ,  1.111,  1.212,  1.313,  1.414,  1.515,
        1.616,  1.717,  1.818,  1.919,  2.02 ,  2.121,  2.222,  2.323,
        2.424,  2.525,  2.626,  2.727,  2.828,  2.929,  3.03 ,  3.131,
        3.232,  3.333,  3.434,  3.535,  3.636,  3.737,  3.838,  3.939,
        4.04 ,  4.141,  4.242,  4.343,  4.444,  4.545,  4.646,  4.747,
        4.848,  4.949,  5.051,  5.152,  5.253,  5.354,  5.455,  5.556,
        5.657,  5.758,  5.859,  5.96 ,  6.061,  6.162,  6.263,  6.364,
        6.465,  6.566,  6.667,  6.768,  6.869,  6.97 ,  7.071,  7.172,
        7.273,  7.374,  7.475,  7.576,  7.677,  7.778,  7.879,  7.98 ,
        8.081,  8.182,  8.283,  8.384,  8.485,  8.586,  8.687,  8.788,
        8.889,  8.99 ,  9.091,  9.192,  9.293,  9.394,  9.495,  9.596,
        9.697,  9.798,  9.899, 10.   ])

In [7]:
np.set_printoptions(threshold=10) # 不会打印所有的元素
np.linspace(0,10,100)

array([ 0.   ,  0.101,  0.202, ...,  9.798,  9.899, 10.   ])