In [2]:
#中位数： 将数据按顺序排列起来，形成一个数列，居于数列中间位置的那个数据
#众数 是在一组数据中，出现次数最多的数据
import numpy as np
arr=np.random.randint(1,10,(10,))
arr

array([8, 5, 7, 4, 8, 3, 8, 8, 3, 3])

In [3]:
np.median(arr)

6.0

In [4]:
np.sort(arr)

array([3, 3, 3, 4, 5, 7, 8, 8, 8, 8])

In [5]:
np.bincount(arr)  # 0 出现0次 1 出现0次  2 出现0次  3 出现3次 4 出现1次 5出现1次 6 出现0次 7 出现1次 8 出现4次

array([0, 0, 0, 3, 1, 1, 0, 1, 4], dtype=int64)

In [6]:
bc=np.bincount(arr) 
np.argmax(bc)# 出现次数最多的数

8