In [1]:
# 二分位数、 四分位数、百分位数
import numpy as np
arr=np.random.randint(1,10,(15,))
arr

array([2, 9, 3, 5, 6, 1, 5, 1, 8, 3, 6, 2, 7, 8, 9])

In [2]:
np.median(arr)  # 中位数

5.0

In [3]:
np.sort(arr)

array([1, 1, 2, 2, 3, 3, 5, 5, 6, 6, 7, 8, 8, 9, 9])

In [4]:
np.percentile(arr,q=50)

5.0

In [5]:
np.percentile(arr,q=75)  # 

7.5

In [6]:
np.percentile(arr,q=90)

8.6

In [7]:
np.percentile(arr,q=100)

9.0

In [8]:
np.percentile(arr,q=[20,50,75,90,100])

array([2. , 5. , 7.5, 8.6, 9. ])