In [2]:
#  相关系数是研究变量之间线性相关程度的量 比较常见的是皮尔逊想换系数，一般用字母r表示
import numpy as np
arr =np.array([[1,2],[2,3.8]]) # 二维数组
arr

array([[1. , 2. ],
       [2. , 3.8]])

In [3]:
np.corrcoef(arr[:,0],arr[:,1]) # arr[:,0] 第一列   arr[:,1 ] 第二列

array([[1., 1.],
       [1., 1.]])

In [4]:
arr=np.array([[1,2],[2,0.2]])
arr

array([[1. , 2. ],
       [2. , 0.2]])

In [5]:
np.corrcoef(arr[:,0],arr[:,1])

array([[ 1., -1.],
       [-1.,  1.]])

In [6]:
arr=np.random.randint(1,10,(4,5))

In [7]:
arr

array([[8, 3, 3, 7, 9],
       [7, 8, 4, 4, 1],
       [4, 8, 7, 6, 4],
       [6, 5, 3, 6, 1]])

In [8]:
np.corrcoef(arr[:,2],arr[:,4])  # 第二列  第四列

array([[ 1.      , -0.081633],
       [-0.081633,  1.      ]])