In [3]:
import numpy as np
arr=np.array([0.,1.,np.nan,3.,np.nan,np.nan,6.,7.,8.,9.])
arr

array([ 0.,  1., nan,  3., nan, nan,  6.,  7.,  8.,  9.])

In [4]:
np.isnan(arr)

array([False, False,  True, False,  True,  True, False, False, False,
       False])

In [5]:
np.where(np.isnan(arr))

(array([2, 4, 5], dtype=int64),)