In [5]:
#  创建NumPy数组
import numpy as np
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

In [2]:
type(v)

numpy.ndarray

In [6]:
m = np.array([[1,2],[3,4]])  # 二维数组
m

array([[1, 2],
       [3, 4]])

In [4]:
type(m)

numpy.ndarray

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(10,110,10) # 不包括右端点

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [9]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [10]:
np.linspace(1,10,20) # 离散20个点  包括右端点

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])