In [1]:
import numpy as np
arr = np.array([[ 0., np.nan, 2., 3.],
 [ 4., 5., np.nan, 7.],
 [ 8., 9., 10., 11.],
 [12., 13., np.nan, 15.],
 [16., 17., np.nan, 19.],
 [20., 21., 22., 23.]])
arr

array([[ 0., nan,  2.,  3.],
       [ 4.,  5., nan,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., nan, 15.],
       [16., 17., nan, 19.],
       [20., 21., 22., 23.]])

In [2]:
masked=np.isnan(arr,)
masked

array([[False,  True, False, False],
       [False, False,  True, False],
       [False, False, False, False],
       [False, False,  True, False],
       [False, False,  True, False],
       [False, False, False, False]])

In [3]:
np.sum(masked,axis=1) #  行

array([1, 1, 0, 1, 1, 0])

In [4]:
masked2 = np.sum(masked, axis=1) == 0
masked2

array([False, False,  True, False, False,  True])

In [5]:
arr[masked2,:]   #提取无缺失值的行

array([[ 8.,  9., 10., 11.],
       [20., 21., 22., 23.]])

In [6]:
#  上述的方法可以简写为
m = np.sum(np.isnan(arr), axis=1) == 0
arr[m]  

array([[ 8.,  9., 10., 11.],
       [20., 21., 22., 23.]])

In [7]:
m = np.sum(np.isnan(arr), axis=1)> 0  #  同理 有缺失值的行
arr[m] 

array([[ 0., nan,  2.,  3.],
       [ 4.,  5., nan,  7.],
       [12., 13., nan, 15.],
       [16., 17., nan, 19.]])