In [1]:
import numpy as np
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [2]:
np.ones((3,5))==1

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [3]:
np.zeros((3,5))==1

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])