In [4]:
import numpy as np
np.arange(20)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [5]:
na2=np.arange(20)
na2.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [18]:
na2=na2.reshape(4,5)
na2[:,[0,3,2,1,4]]   # 第2列和第4列交换位置

array([[ 0,  3,  2,  1,  4],
       [ 5,  8,  7,  6,  9],
       [10, 13, 12, 11, 14],
       [15, 18, 17, 16, 19]])

In [20]:
mask=list(range(5))
mask[1],mask[3]=mask[3],mask[1]
mask

[0, 3, 2, 1, 4]

In [21]:
na2[:,mask] # 交换列

array([[ 0,  3,  2,  1,  4],
       [ 5,  8,  7,  6,  9],
       [10, 13, 12, 11, 14],
       [15, 18, 17, 16, 19]])

In [23]:
mask=list(range(4))
mask[1],mask[3]=mask[3],mask[1]
mask

[0, 3, 2, 1]

In [25]:
na2[mask,:]  # 交换行

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9]])