In [2]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
wid = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[1]) # 获取第一列数据
wid

array([3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. ,
       3. , 4. , 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
       3.4, 3.5, 3.4, 3.2, 3.1, 3.4, 4.1, 4.2, 3.1, 3.2, 3.5, 3.1, 3. ,
       3.4, 3.5, 2.3, 3.2, 3.5, 3.8, 3. , 3.8, 3.2, 3.7, 3.3, 3.2, 3.2,
       3.1, 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2. , 3. , 2.2, 2.9, 2.9,
       3.1, 3. , 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, 2.8, 2.9, 3. , 2.8, 3. ,
       2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3. , 3.4, 3.1, 2.3, 3. , 2.5, 2.6,
       3. , 2.6, 2.3, 2.7, 3. , 2.9, 2.9, 2.5, 2.8, 3.3, 2.7, 3. , 2.9,
       3. , 3. , 2.5, 2.9, 2.5, 3.6, 3.2, 2.7, 3. , 2.5, 2.8, 3.2, 3. ,
       3.8, 2.6, 2.2, 3.2, 2.8, 2.8, 2.7, 3.3, 3.2, 2.8, 3. , 2.8, 3. ,
       2.8, 3.8, 2.8, 2.8, 2.6, 3. , 3.4, 3.1, 3. , 3.1, 3.1, 3.1, 2.7,
       3.2, 3.3, 3. , 2.5, 3. , 3.4, 3. ])

In [3]:
wid.shape


(150,)

In [5]:
smax = np.max(wid)
smin = np.min(wid)
s = (wid - smin) / (smax-smin)
s

array([0.625     , 0.41666667, 0.5       , 0.45833333, 0.66666667,
       0.79166667, 0.58333333, 0.58333333, 0.375     , 0.45833333,
       0.70833333, 0.58333333, 0.41666667, 0.41666667, 0.83333333,
       1.        , 0.79166667, 0.625     , 0.75      , 0.75      ,
       0.58333333, 0.70833333, 0.66666667, 0.54166667, 0.58333333,
       0.41666667, 0.58333333, 0.625     , 0.58333333, 0.5       ,
       0.45833333, 0.58333333, 0.875     , 0.91666667, 0.45833333,
       0.5       , 0.625     , 0.45833333, 0.41666667, 0.58333333,
       0.625     , 0.125     , 0.5       , 0.625     , 0.75      ,
       0.41666667, 0.75      , 0.5       , 0.70833333, 0.54166667,
       0.5       , 0.5       , 0.45833333, 0.125     , 0.33333333,
       0.33333333, 0.54166667, 0.16666667, 0.375     , 0.29166667,
       0.        , 0.41666667, 0.08333333, 0.375     , 0.375     ,
       0.45833333, 0.41666667, 0.29166667, 0.08333333, 0.20833333,
       0.5       , 0.33333333, 0.20833333, 0.33333333, 0.375  

In [6]:
smax


4.4

In [7]:
smin

2.0

In [8]:

s = (wid - smin) / wid.ptp()
s

array([0.625     , 0.41666667, 0.5       , 0.45833333, 0.66666667,
       0.79166667, 0.58333333, 0.58333333, 0.375     , 0.45833333,
       0.70833333, 0.58333333, 0.41666667, 0.41666667, 0.83333333,
       1.        , 0.79166667, 0.625     , 0.75      , 0.75      ,
       0.58333333, 0.70833333, 0.66666667, 0.54166667, 0.58333333,
       0.41666667, 0.58333333, 0.625     , 0.58333333, 0.5       ,
       0.45833333, 0.58333333, 0.875     , 0.91666667, 0.45833333,
       0.5       , 0.625     , 0.45833333, 0.41666667, 0.58333333,
       0.625     , 0.125     , 0.5       , 0.625     , 0.75      ,
       0.41666667, 0.75      , 0.5       , 0.70833333, 0.54166667,
       0.5       , 0.5       , 0.45833333, 0.125     , 0.33333333,
       0.33333333, 0.54166667, 0.16666667, 0.375     , 0.29166667,
       0.        , 0.41666667, 0.08333333, 0.375     , 0.375     ,
       0.45833333, 0.41666667, 0.29166667, 0.08333333, 0.20833333,
       0.5       , 0.33333333, 0.20833333, 0.33333333, 0.375  

In [9]:
np.set_printoptions(precision=3)
s = (wid - smin) / wid.ptp()
s

array([0.625, 0.417, 0.5  , 0.458, 0.667, 0.792, 0.583, 0.583, 0.375,
       0.458, 0.708, 0.583, 0.417, 0.417, 0.833, 1.   , 0.792, 0.625,
       0.75 , 0.75 , 0.583, 0.708, 0.667, 0.542, 0.583, 0.417, 0.583,
       0.625, 0.583, 0.5  , 0.458, 0.583, 0.875, 0.917, 0.458, 0.5  ,
       0.625, 0.458, 0.417, 0.583, 0.625, 0.125, 0.5  , 0.625, 0.75 ,
       0.417, 0.75 , 0.5  , 0.708, 0.542, 0.5  , 0.5  , 0.458, 0.125,
       0.333, 0.333, 0.542, 0.167, 0.375, 0.292, 0.   , 0.417, 0.083,
       0.375, 0.375, 0.458, 0.417, 0.292, 0.083, 0.208, 0.5  , 0.333,
       0.208, 0.333, 0.375, 0.417, 0.333, 0.417, 0.375, 0.25 , 0.167,
       0.167, 0.292, 0.292, 0.417, 0.583, 0.458, 0.125, 0.417, 0.208,
       0.25 , 0.417, 0.25 , 0.125, 0.292, 0.417, 0.375, 0.375, 0.208,
       0.333, 0.542, 0.292, 0.417, 0.375, 0.417, 0.417, 0.208, 0.375,
       0.208, 0.667, 0.5  , 0.292, 0.417, 0.208, 0.333, 0.5  , 0.417,
       0.75 , 0.25 , 0.083, 0.5  , 0.333, 0.333, 0.292, 0.542, 0.5  ,
       0.333, 0.417,